[WIP] 89 colony black market
Igmat/SpaceExpatriateReact pull request #105
Opened 2023-10-16 11:32 UTC by angemariya

2023-10-17 17:19 UTC, angemariya commented
Эффект вроде заработал, но есть один момент с тем, что карта активируется даже если комбинаций для показа нет. И еще модалка пока не работает как хочется и ModalManager не доделан, нужно больше времени.

2023-10-17 18:55 UTC, Igmat requested changes
Хорошое начало, но с модал менеджером нужно ещё поработать

2023-10-17 18:55 UTC, Igmat commented on src/Rules/ActionManager.ts
> +    this.activeAction && this.colony.triggers.after(this.activeAction);
кажеться здесь нужен await

2023-10-17 18:55 UTC, Igmat commented on src/Rules/Delivery/index.ts
> +      return new Promise((resolve) => {
не думаю, что это то, что нужно

2023-10-24 13:55 UTC, Igmat requested changes

2023-10-24 13:55 UTC, Igmat commented on src/Rules/Delivery/index.ts
> +      this.resources.addResource(this.selectedResource);
`isResourcePrimitive` проверка больше не нужна здесь

2023-10-24 13:55 UTC, Igmat commented on src/Rules/Delivery/index.ts
> +    //    this.deliveryOption = undefined;
зачем убрала сброс `deliveryOption`?

2023-10-24 13:55 UTC, Igmat commented on src/Rules/Engineering/index.ts
> +  setRemainingActivateDeck = (value: number) => {
учитывая логику этого метода, логичнее использовать глагол `adjust`, а не `set`

2023-10-24 13:55 UTC, Igmat commented on src/Rules/ModalManager.ts
> +    onClose?: () => void;
кажется это лишняя опция

2023-10-24 13:55 UTC, Igmat commented on src/Rules/ModalManager.ts
> +    type?: ModalType = undefined;
по логике остальных параметров этот тоже должен быть приватным, с геттером

2023-10-24 13:55 UTC, Igmat commented on src/Rules/ResourcesModel.ts
>        "tempGarbageResources",
такого свойства в классе вроде бы нет

2023-10-24 13:55 UTC, Igmat commented on src/Rules/ResourcesModel.ts
> +  async tryConsumeResources(resources: Resource[], onConsume: () => void) {
раз уж это у нас асинхронный метод, то логично не использовать в нём колбек, а возвращать булеан (получилось ли потратить ресурсы или нет) и уже в вызывающем коде в зависимости от удачности траты ресурсов вызывать или нет то, что раньше передавалось сюда в качестве колбека

2023-10-24 13:55 UTC, Igmat commented on src/Rules/ResourcesModel.ts
> +    resource: Exclude<ResourcePrimitive, "dark matter">
у нас для этого уже есть тип, который можно импортировать

2023-10-24 13:55 UTC, Igmat commented on src/Rules/Terraforming/index.ts
> +    if (isCardType(this.terraformingOption)) {
`isCardType` выглядит как лишняя проверка теперь

2023-10-24 13:55 UTC, Igmat commented on src/Rules/Terraforming/index.ts
> +  terraformingOption?: (typeof TerraformingOption)[number];
Это же повторение `missionType`

2023-10-24 13:55 UTC, Igmat commented on src/Rules/Terraforming/index.ts
> +const TerraformingOption = ["delivery", "engineering", "terraforming", "military"] as const;
Я думал ты сделаешь такой массив там где у нас определён тип `CardType`

2023-10-24 17:39 UTC, angemariya commented on src/Rules/Engineering/index.ts
> +  setRemainingActivateDeck = (value: number) => {
Это пришло из Настиной ветки, но я переименую

2023-10-26 07:06 UTC, Igmat requested changes

2023-10-26 07:06 UTC, Igmat commented on src/Rules/card-types.ts
> +export const TerraformingOption = ["delivery", "engineering", "terraforming", "military"] as const;
Это же массив `CardType` строк, его стоит так и назвать (в множественном числе)

2023-10-26 07:48 UTC, Igmat approved these changes

2023-10-26 07:48 UTC, merged