fix: fixed names and count FinishCounter
Igmat/SpaceExpatriateReact pull request #28
Opened 2023-09-11 05:56 UTC by KiraSeletska

2023-09-13 08:27 UTC, Igmat requested changes

2023-09-13 08:27 UTC, Igmat commented on src/Rules/Engineering/index.ts
> +        this.table.takeCard(this.hand.addCardsToTempDrop(card));
Почему работем с деливери экшеном, а логику поменяли для инжиниринга?:)

2023-09-13 08:27 UTC, Igmat commented on src/Rules/HandModel.ts
> +  addCardsToTempDrop = (ind: number) => {
Ну, иногда нам карту нужно и сразу полностью сбросить.

2023-09-13 08:27 UTC, Igmat commented on src/Rules/ResourcesModel.ts
> +  resetGarbage = () => {
А как это у нас вообще может произойти?

2023-09-13 08:27 UTC, Igmat commented on src/Rules/ResourcesModel.ts
> +  calculateStartEnergy = () => {
стартова енергия у нас 0, я думаю тут ты перемудрила

2023-09-13 08:49 UTC, KiraSeletska commented on src/Rules/Engineering/index.ts
> +        this.table.takeCard(this.hand.addCardsToTempDrop(card));
DropCard в Hand быр переписан и поменял название на  addCardsToTempDrop. По сути разница в том, что появилось промежуточное хранилище, которое очищается автоматически при смене раунда. Надо было оставить оба? Надо было вообше не трогать руку, и все сделать в DeliveriAction, так?

2023-09-13 08:52 UTC, KiraSeletska commented on src/Rules/ResourcesModel.ts
> +  resetGarbage = () => {
При выборе очистки мусора нужна была так же отмена. Сохраняется состояние мусора при переходе на каждый раунд. Игрок выбирает сбросить каокй-то ресурс, меняет мнение, ресурсы в гарбедже востанавливаются, ресетом откатываются в предыдущее состояние

2023-09-13 08:54 UTC, KiraSeletska commented on src/Rules/ResourcesModel.ts
> +  calculateStartEnergy = () => {
calculateStartEnergy - считает только карты Start, energy изначально просто 0

2023-09-13 09:20 UTC, KiraSeletska commented on src/Rules/Engineering/index.ts
> +        this.table.takeCard(this.hand.addCardsToTempDrop(card));
исправла, залила новый

2023-09-14 11:28 UTC, Igmat requested changes

2023-09-14 11:28 UTC, Igmat commented on src/Rules/ResourcesModel.ts
> +  calculateStartEnergy = () => {
Так в том-то и суть, у нас никакой стартовой енергии нет пока карты `start` не активированы, значить считать просто нечего.

2023-09-14 11:28 UTC, Igmat commented on src/Rules/ResourcesModel.ts
> +  resetGarbage = () => {
У нас "ресет" не должен отменять выбор опции т.е. если выбрана очистка, то это не меняется при ресете, отменяеться только результат применения карт со стола/руки.

2023-09-14 11:28 UTC, Igmat commented on src/Rules/HandModel.ts
> + dropCards = (ind: number) => {
`dropCard` было всё-таки лучше т.к. сбрасываем мы только 1 карту, а не несколько.

2023-09-14 11:44 UTC, KiraSeletska commented on src/Rules/ResourcesModel.ts
> +  resetGarbage = () => {
исправила

2023-09-14 11:44 UTC, KiraSeletska commented on src/Rules/ResourcesModel.ts
> +  resetGarbage = () => {
исправила

2023-09-14 11:46 UTC, KiraSeletska commented on src/Rules/ResourcesModel.ts
> +  calculateStartEnergy = () => {
просто у нас напсиано везде вот так:

2023-09-14 11:47 UTC, KiraSeletska commented on src/Rules/ResourcesModel.ts
> +  calculateStartEnergy = () => {
All players are taking resources are displayed on their own Delivery Station Module cards and discard from your resources the same number and type as contained in Space Garbage (automatically)
activating cards counter(0 to all cards, 1 to start)
Calculate energy (automatically) 
&
- [X] -> создается StartMap {ключ=ID: значение=1} с картами  Start на столе

2023-09-14 11:50 UTC, KiraSeletska commented on src/Rules/HandModel.ts
> + dropCards = (ind: number) => {
исправила

2023-09-14 15:30 UTC, Igmat requested changes

2023-09-14 15:30 UTC, Igmat commented on src/Rules/Delivery/index.ts
> -    this.resources.dropResources();
А ресет ресурсов нам всё равно нужен т.к. использование карт меняет же ресурсы, которые тебе доступны.

2023-09-14 16:05 UTC, KiraSeletska commented on src/Rules/Delivery/index.ts
> -    this.resources.dropResources();
Исправила, отправила. Два варианта: закоментированные - доп сохранение, актуальный - изменила функцию получения ресурсов: при получение обнуляю, что бы при повторном вызове они не сумировались. Мне кажется второй вариант более простым, но если я что-то не учла - сможем использовать законментированный

2023-09-14 16:06 UTC, Igmat requested changes

2023-09-14 16:06 UTC, Igmat commented on src/Rules/ResourcesModel.ts
>      if (this.table.delivery.length === 0) return;
А это не лишняя проверка

2023-09-14 16:13 UTC, KiraSeletska commented on src/Rules/ResourcesModel.ts
>      if (this.table.delivery.length === 0) return;
Если это вопрос - мы ее аргументировано оставляли, но сейчас аргументы в точности сложно вспомнить. Мне кажется неуместной, ведь при выборе деливери хоть одна крата, но будет. Не трогала, т.к.  утвердили. Удалить?

2023-09-15 06:40 UTC, KiraSeletska commented on src/Rules/ResourcesModel.ts
>      if (this.table.delivery.length === 0) return;
Удалила, залила

2023-09-15 07:06 UTC, merged