WIP feat: add modalwindow & delivery engeniring
Igmat/SpaceExpatriateReact pull request #29
Opened 2023-09-11 07:11 UTC by mirage109

delivery phase engeniring cards logic

2023-09-13 08:16 UTC, Igmat requested changes
Дополнительно к остальным комментариям:
Из метода `activateCardOnTable` работу с `engineering` желательно вынести в отдельный метод (или может даже несколько), ведь на этом экшене могут активировать и другие типы карт (`terraforming`).
Увеличение енергии тоже можно вынести в отдельный метод т.к. каждый раз как мы увеличиваем энергию, происходит ещё и пересчёт оставшихся активаций других карт.

2023-09-13 08:16 UTC, Igmat commented on src/Rules/Delivery/index.ts
> +      const entryPoint = card.entryPoint as ResourcePrimitive;
зачем преоброзование в `ResourcePrimitive`?

2023-09-13 08:16 UTC, Igmat commented on src/Rules/Delivery/index.ts
> +          this.resources.points.round++;
Поинты тут увеличиваються только тогда, когда это указано на карте и на количество, которое на ней указано

2023-09-13 08:16 UTC, Igmat commented on src/Rules/Delivery/index.ts
> +          this.resources.points.round++;
Поинты тут увеличиваються только тогда, когда это указано на карте и на количество, которое на ней указано

2023-09-13 08:16 UTC, Igmat commented on src/Rules/Delivery/index.ts
> +      this.calculateResourcesCombination(); //&& this.tryNext()
Этот кусок кажеться устаревшим

2023-09-13 08:16 UTC, Igmat commented on src/Rules/card-types.ts
> +    entryPoint?: ResourcePrimitive,
Есть уверенность, что это правильный тип?

2023-09-13 08:40 UTC, mirage109 commented on src/Rules/CardDefinitions/engineering.ts
> +    { connection: "continue", entryPoint: "fuel", exitPoint: ["machinery", "nanotechnologies"], name: "SPECIALIZED SPACE FACTORY", quantity: 2 },
Это не ошибка, это нормальный способ достучаться до длины масива экзит поинта
Смотри - у нас есть два кейса экзит поинта: один или один из двух на выбор.

Если экзит поинт один - то мы его считали и записали.

Если их два - то мы считываем и уже через модалку пользователь выбирает какой.

Убрав этот в масив в масиве, я получила два варианта:
1. масив из одного элемента 
2. масив из двух элементов (или больше)

в случае №1 мы не вызываем модалку, так как мой метод  gainResources понимает, что надо просто получить ресурс.

в случае №2 мой метод видит, что масив больше одного элемента -  и вызывается модалка, в которой уже нужно выбрать нужный ресурс, и уже после выбора он записывается

2023-09-13 08:41 UTC, mirage109 commented on src/Rules/Delivery/index.ts
> +      this.calculateResourcesCombination(); //&& this.tryNext()
Это вообще не мое, я его просто не трогала. могу удалить

2023-09-13 08:47 UTC, mirage109 commented on src/Rules/Delivery/index.ts
> +      const entryPoint = card.entryPoint as ResourcePrimitive;
убрала

2023-09-13 08:51 UTC, mirage109 commented on src/Rules/Delivery/index.ts
> +          this.resources.points.round++;
fixed

2023-09-13 08:51 UTC, mirage109 commented on src/Rules/Delivery/index.ts
> +          this.resources.points.round++;
fixed

2023-09-13 09:06 UTC, mirage109 commented
Метод вынесла, баги пофиксила, на вопросы ответила)

2023-09-14 05:51 UTC, Igmat requested changes
Отличный фикс, но можно улучшить ещё:
`activateEngineeringCard` состоит из трёх больших кусков, которые не пересекаються вообще по типу конекшена. Давай разобьём одну большую функцию в таком случае на три для каждого отдельного случая.

2023-09-14 05:58 UTC, Igmat commented on src/Rules/CardDefinitions/engineering.ts
> +    { connection: "continue", entryPoint: "fuel", exitPoint: ["machinery", "nanotechnologies"], name: "SPECIALIZED SPACE FACTORY", quantity: 2 },
Хорошо, твою логику я понял. Идея правильная и хорошая, но она исходит из предположения, что гейм-дизайн и набор карт меняться не будут, которое, к сожалению, неверное.

Именно эту часть нужно вернуть к исходному состоянию, сам алгоритм `gainResources` измениться не существенно, оставлю там более детальное пояснение.

2023-09-14 06:02 UTC, Igmat commented on src/Rules/card-types.ts
> +    entryPoint?: ResourcePrimitive,
Гуд поинт. Но в будущем будут эксперименты с гейм-дизайном и балансом, поэтому нужно в этом месте чуть больше гибкости, а значит код должен уметь с этим работать. Энтри поинт всё-таки не примитив, а полноценный ресурс.

2023-09-14 06:13 UTC, Igmat requested changes
Условия и логику начисления ресурсов нужно немного поменять, но сама идея со `step = "resources"` отличная. Много где дальше пригодится.

2023-09-14 06:13 UTC, Igmat commented on src/Rules/Delivery/index.ts
> +    if (card.exitPoint?.length === 1) {
Для более правильного и гибкого алгоритма, здесь нужно проверять не длинну массива `exitPoint`, а наличие в нём вложенных массивов (что значит, что там есть ресурсы на выбор игрока).

Если же вложенных массивов нет, значит там только примитивы, а значит вариант только 1 и можно его сразу же и посчитать.

2023-09-14 06:13 UTC, Igmat commented on src/Rules/Delivery/index.ts
> +     this.resources.gainResource(card.exitPoint[0]);
Карта может давать больше одного ресурса.

2023-09-14 06:13 UTC, Igmat commented on src/Rules/Delivery/index.ts
> +    } else {
В нашем общем стиле, мы избегаем `else` и просто делаем `return` в положительной ветке.

2023-09-14 10:36 UTC, mirage109 commented on src/Rules/card-types.ts
> +    entryPoint?: ResourcePrimitive,
вернула как было

2023-09-14 10:37 UTC, mirage109 commented on src/Rules/CardDefinitions/engineering.ts
> +    { connection: "continue", entryPoint: "fuel", exitPoint: ["machinery", "nanotechnologies"], name: "SPECIALIZED SPACE FACTORY", quantity: 2 },
вернула как было

2023-09-14 13:12 UTC, mirage109 commented on src/Rules/Delivery/index.ts
> +     this.resources.gainResource(card.exitPoint[0]);
ок, перебираю все и проверяю тип

2023-09-14 13:13 UTC, mirage109 commented on src/Rules/Delivery/index.ts
> +    } else {
ок

2023-09-14 14:50 UTC, mirage109 commented on src/Rules/card-types.ts
> +    entryPoint?: ResourcePrimitive,
поменяла всю логику списывания ресурсов. сделала метод consumeResources - который проверяет энтри поинт - один он или несколько

2023-09-14 15:16 UTC, mirage109 commented
1. Вынесла в отдельные методы обработку разных connection
2. Вернула типы как было
3. Создала метод consumeResources, который учитывает варианты entrypoint  (если один, если несколько)
4. exitpoint пока обрабатывает правильно если он один, над сценарием, когда их несколько или на выбор еще медитирую

2023-09-14 15:25 UTC, mirage109 commented on src/Rules/Delivery/index.ts
> +    if (card.exitPoint?.length === 1) {
один посчитала

2023-09-14 15:53 UTC, Igmat requested changes
У тебя тело методов `processConnection` и `consumeResources` полностью находиться внутри `if`, в таких случаях мы интвертируем условие и делаем сразу ретурн, вместо того, что бы весь код держать внутри ифа.

2023-09-14 15:53 UTC, Igmat commented on src/Rules/Delivery/index.ts
> +          if (typeof el === "string") {
это уже лишняя проверка т.к. `entryPoint` это `Resource`, а значит если он массив, то его внутренности это `ResourcePrimitive`, который просто строка

2023-09-14 15:53 UTC, Igmat commented on src/Rules/Delivery/index.ts
> +            this.resources.playerResources[el]--;
Ну, по логике, что `ResourcePrimitive[]` как один из вариантов `Resource` означает выбор или-или, тут должен сниматься только 1 ресурс, а ты снимаешь - оба, будто здесь это означает `И`.

2023-09-14 15:53 UTC, Igmat commented on src/Rules/Delivery/index.ts
> +            if (typeof el === "string") {
Опять лишняя проверка

2023-09-14 16:11 UTC, mirage109 commented on src/Rules/Delivery/index.ts
> +          if (typeof el === "string") {
ок

2023-09-15 08:48 UTC, Igmat requested changes
Код для подсчёта доступных комбинаций достаточно сложный для понимания, его нужно вынести и отдельно покрыть тестами.

2023-09-15 08:48 UTC, Igmat commented on src/Rules/Delivery/index.ts
> +  areCombinationsEqual(
Здесь не используется `this` и функциональность этого метода очень ОБЩАЯ.
Этой функции незачем быть методом класса и его стоит вынести отдельно в файл утилит или чего-то подобного.

2023-09-15 08:48 UTC, Igmat commented on src/Rules/Delivery/index.ts
> +  removeDuplicateCombinations(combinations: Array<ResourcePrimitive[]>) {
Аналогично с `areCombinationsEqual`

2023-09-15 08:48 UTC, Igmat commented on src/Rules/Delivery/index.ts
> +    let combinations: Array<ResourcePrimitive[]> = [[]];
Часть которая занимается собственно подсчётом комбинаций достаточно общая и не требует `this`. Стоит вынести в утилиты с отдельными функциями.

2023-09-15 10:12 UTC, mirage109 commented on src/Rules/Delivery/index.ts
> +  areCombinationsEqual(
вынесла

2023-09-15 10:12 UTC, mirage109 commented on src/Rules/Delivery/index.ts
> +  removeDuplicateCombinations(combinations: Array<ResourcePrimitive[]>) {
вынесла в Utils.ts

2023-09-15 10:12 UTC, mirage109 commented on src/Rules/Delivery/index.ts
> +    let combinations: Array<ResourcePrimitive[]> = [[]];
Ок

2023-09-15 10:17 UTC, mirage109 commented
Я вынесла три функции из DAM: generateCombinations, removeDuplicateCombinations, areCombinationsEqual,
В removeDuplicateCombinations  и areCombinationsEqual порешала с типами. теперь они не привязаны к ресурсПримитив.

В generateCombinations с типами сложнее, абстрагироваться от ресурсПримитив[ ] не получается пока.

2023-09-15 11:17 UTC, Igmat requested changes

2023-09-15 11:17 UTC, Igmat commented on src/Rules/Delivery/index.ts
> +    const combinations = generateCombinations(card);
просто передавай здесь `card.exitPoint`, а не `card` и получится сделать дженерик

2023-09-15 11:17 UTC, Igmat commented on src/Utils/index.ts
> +  card.exitPoint!.forEach((el) => {
заодно избавишься здесь от восклицательного знака, что сделает метод более типобезопасным

2023-09-15 13:51 UTC, mirage109 commented
1. В утилитах убрала зависимость он нашей игры
2. Прописала логику терраформинг карт
3. Прописала и обновила методы списания и начиления ресурсов, если вариантов несколько.
4. Для списания ресурсов сделала так, что юзеру показываются только те комбинации на которые у него хватает денег.

2023-09-18 07:01 UTC, Igmat requested changes

2023-09-18 07:01 UTC, Igmat commented on src/ControlPanel/index.tsx
> +            gameState.round.onSelect!(resource);
Восклицательный знак лучше избегать в таких ситуациях. Тем более, что добавить проверку не сложно;)

2023-09-18 09:00 UTC, mirage109 commented on src/Utils/index.ts
> +export const toArrayArray = (array: Resource[]): ResourcePrimitive[][] => {
готово

2023-09-18 09:36 UTC, mirage109 commented on src/ControlPanel/index.tsx
> +            gameState.round.onSelect!(resource);
готово

2023-09-18 10:18 UTC, Igmat approved these changes

2023-09-18 10:18 UTC, merged