[WIP]feat: add StartWindow
Igmat/SpaceExpatriateReact pull request #31
Opened 2023-09-15 11:14 UTC by KiraSeletska

1. Какой вид роутинга оставить? 
2. При перезагрузке страницы я остаюсь в игре, а не перехожу на стартовую страницу, думаю, так быть не должно
3. Вообще не уверена в том, что сделала
Спасибо

2023-09-15 11:25 UTC, Igmat requested changes

2023-09-15 11:25 UTC, Igmat commented on src/index.tsx
> +import { GamePage } from "./components/TestGamePage";
Почему страница в папке компонентов? И почему она называется `TestGame`?

2023-09-15 11:25 UTC, Igmat commented on src/index.tsx
> +import { StartWindow } from "./components/StartWindow";
Зачастую это называют `Home`, а не стартвиндоу. Ну, и в компонентах странице делать нечего:)

2023-09-15 11:28 UTC, Igmat commented
1. Любой (такой норм)
2. ну, если в адрессной строке у тебя `localhost:3000/game`, то это как раз ожидаемое и правильное поведение
3. Всё гуд на первый взгляд

2023-09-15 11:29 UTC, KiraSeletska commented on src/index.tsx
> +import { StartWindow } from "./components/StartWindow";
Переименовала и вынесла. Оставить HomePage в папке src или создать в src папку для страниц и вложить стартовую туда?

2023-09-15 12:27 UTC, Igmat requested changes
хорошо, только не надо повторять Page везде, оно и так находиться в папке Pages;)

2023-09-18 06:45 UTC, Igmat approved these changes

2023-09-18 06:45 UTC, merged