[WIP] refactoring
Igmat/SpaceExpatriateReact pull request #37
Opened 2023-09-18 14:27 UTC by mirage109

2023-09-19 08:04 UTC, Igmat requested changes
Методы `setStartValueToZero`, `decreaseMiddleValue`, `changeFinishCounter` лучше объеденить и инкапсулировать в `ResourceModel`. Вместо использования разных методов лучше иметь один метод `useCardConnection`, который уже будет отвечать за то как меняются `engineeringMaps` и энергия.

2023-09-19 08:04 UTC, Igmat commented on src/Rules/RoundManager.ts
> +  setRoundResourceStep(params: ResourcePrimitive[][], onSelect: (selected: ResourcePrimitive[]) => void) {
`startResourceStep` как название было бы лучше.

2023-09-19 08:04 UTC, Igmat commented on src/Rules/RoundManager.ts
> +  setParams(params: ResourcePrimitive[][]) {
Лучше обойтись без этого метода.

2023-09-19 08:04 UTC, Igmat commented on src/Rules/Delivery/index.ts
> +    this.resources.resetRoundPoints(); // был ресет всех очков, а надо только раунда
Все обращения к ресурсам здесь имеет смысл инкапуслировать в один метод модели ресурсов.

2023-09-19 13:46 UTC, mirage109 commented on src/Rules/ResourcesModel.ts
> +  increaseAllMiddleValues() {
Ок

2023-09-19 14:05 UTC, mirage109 commented on src/Rules/RoundManager.ts
> +  setStep(step: Step) {
ок

2023-09-19 14:22 UTC, mirage109 commented on src/Rules/Delivery/index.ts
> +    this.resources.resetRoundPoints(); // был ресет всех очков, а надо только раунда
ок

2023-09-19 14:27 UTC, mirage109 commented on src/Rules/Delivery/index.ts
> +  canConsumeResources(resources: ResourcePrimitive[]) {// перевіряємо чи є в гравця кошти для виконання карти (списали /не зайшли в мінус?/повернули)
ок

2023-09-20 07:44 UTC, Igmat commented on src/Rules/Delivery/index.ts
>            this.resources.calculateRoundPoints(card);
А не имеет ли смысл этот колбек перенести во внутренню логику `tryConsumeResources`?

2023-09-20 07:45 UTC, Igmat commented on src/Rules/Delivery/index.ts
> +    this.resources.createEngineeringMaps(this.table.engineering); // потеряли в прошлой версии, что мы обнуляем счетчики
Эта часть ресета отлично бы смотрелась внутри метода `resetRoundState`

2023-09-20 07:50 UTC, Igmat commented on src/Rules/Delivery/index.ts
>    processEndConnection(card: EngineeringCard) {
`processStartConnection`, `processContinueConnection`, `processEndConnection` теперь стали слишком похожи, как мы можем избежать повторения?

2023-09-20 07:51 UTC, Igmat commented on src/Rules/ResourcesModel.ts
>    public energy = 0;
стоит переделать с помощью геттера, что бы не было возможности исправлять значение снаружи.

2023-09-20 08:08 UTC, mirage109 commented on src/Rules/Delivery/index.ts
> +    this.resources.createEngineeringMaps(this.table.engineering); // потеряли в прошлой версии, что мы обнуляем счетчики
ок

2023-09-20 08:12 UTC, mirage109 commented on src/Rules/ResourcesModel.ts
>    public energy = 0;
ок

2023-09-20 08:47 UTC, mirage109 commented on src/Rules/Delivery/index.ts
>    processEndConnection(card: EngineeringCard) {
можем

2023-09-20 08:59 UTC, mirage109 commented on src/Rules/Delivery/index.ts
>            this.resources.calculateRoundPoints(card);
вынесла кол-бек в отдельную функцию, кол бек для терраформинг карт и для  инжиниринг карт немного разный, поэтому пока что мы его передаем аргументом.

2023-09-20 09:10 UTC, mirage109 commented on src/Rules/Delivery/index.ts
>            this.resources.calculateRoundPoints(card);
Нет, не имеет. Так как трайконсьюм ресурс  -  ответчает за одно дело, делает его хорошо, его задача проверить возьможность сожрать ресурсы. И оно не зависит от карт, про карты этот метод ничего не знает.

А уже аргумент-коллбек  знает, что делать дальше.

2023-09-20 09:16 UTC, mirage109 commented on src/Rules/Delivery/index.ts
>            this.resources.calculateRoundPoints(card);
И если идти дальше в черную материю, то про нее нужно будет знать только методу  трайконсьюм ресурс - так как это будет + комбинация, а другие мметоды просто получат набор ресурсов для съедения.

2023-09-20 10:04 UTC, Igmat requested changes

2023-09-20 10:04 UTC, Igmat commented on src/Rules/Delivery/index.ts
> +      if (this.resources.engineeringMaps.Start[card.id] === 0) return;
Прекрасно! Идеально будет, если вместо двух ифов будет один с &&

2023-09-20 10:22 UTC, Igmat commented on src/Rules/Delivery/index.ts
>            this.resources.calculateRoundPoints(card);
Согласен

2023-09-20 12:29 UTC, Igmat approved these changes
LGTM

2023-09-20 12:32 UTC, merged