[WIP]Cherry from SaveToLS
Igmat/SpaceExpatriateReact pull request #46
Opened 2023-09-21 14:14 UTC by KiraSeletska

2023-09-22 07:06 UTC, Igmat requested changes

2023-09-22 07:06 UTC, Igmat commented on src/utils.ts
> +  //return localStorage.getItem(key);
уже лучше, но здесь стоит добавить второй аргумент, которые будет значением по умолчанию

2023-09-22 07:06 UTC, Igmat commented on src/Rules/RoundManager.ts
> +  //  onSelect: (selected: ResourcePrimitive[]) => void
Я понимаю, что ты тут просто эксперементировала. Такие вещи, лучше потом возвращать к исходному виду.

2023-09-22 07:06 UTC, Igmat commented on src/Rules/Delivery/index.ts
> +  selectedCard?: CardDefinition | any = readFromLS("selectedCard");//change
`| any` не делай так, пожалуйста, от этого теряется смысл в типизации.

2023-09-22 07:06 UTC, Igmat commented on src/Rules/Delivery/index.ts
> +    this.selectedCard = card;
Чего ты этим пытаешься добиться? + судя по всему, ты забыла эту переменную очищать

2023-09-22 07:09 UTC, KiraSeletska commented on src/Board/ResourcesDeck/index.tsx
> +  const endGame = () => {
Это не его место) Просто искала место с подходящими импортами, что бы не создавать новые. В дальнейшем переедет туда, куда надо

2023-09-25 07:00 UTC, Igmat requested changes

2023-09-25 07:00 UTC, Igmat commented on src/utils.ts
> + localStorage.getItem(key) !== null ? localStorage.getItem(key) : defaultValue
Не стоит читать из стораджа дважды, лучше читать один разу в переменную и потом её использовать

2023-09-27 07:27 UTC, closed without merging