feat: issue #75
Igmat/SpaceExpatriateReact pull request #97
Opened 2023-10-11 09:00 UTC by mirage109

2023-10-11 19:04 UTC, Igmat requested changes
Некоторые замечания, которые внезапно сильно увеличивают задачу + надо порешать конфликты

2023-10-11 19:04 UTC, Igmat commented on src/Player/Table/index.tsx
> -      {/*  {(["delivery", "engineering", "terraforming", "military"] as const).map(el =>
Удаления закомментированного кода - похвально, но всё таки лучше было бы его раскомментировать, поправить и убрать другой код (незакомментированный), который его заменяет

2023-10-11 19:04 UTC, Igmat commented on src/Player/Table/index.tsx
> +        (props.round.phase === "delivery" ||
Кажеться условия уже настолько разрослись, что их самое время вынести в модель (`RoundManager`), а не расширать логку вьюшки

2023-10-12 15:17 UTC, Igmat requested changes
Выглядит отлично, но пара минорных замечаний + конфликты

2023-10-12 15:17 UTC, Igmat commented on src/Player/Table/index.tsx
> +          <div className={styles.cardsContainer}>
Этому диву по идее не помешает `key`. Разве линтер здесь не ругается?

2023-10-12 15:17 UTC, Igmat commented on src/Player/Table/index.tsx
> +        <button className={styles.endTurnButton} onClick={props.action.tryNext}>
Понимаю, что логика тут супер-примитивная, но я бы развёл это на две разных кнопки, а не одна кнопка в которой текст меняется

2023-10-12 15:28 UTC, mirage109 commented on src/Player/Table/index.tsx
> +          <div className={styles.cardsContainer}>
линтер даже слова не сказал)

2023-10-12 15:51 UTC, Igmat commented on src/Player/Table/index.tsx
> +      {props.round.step === "performing" &&
Ты не до конца поняла идею. Должно быть 2 строки подобные к 49-ой, а не тернарка

2023-10-12 15:51 UTC, Igmat commented on src/Rules/RoundManager.ts
> +
Лишняя строка;)

2023-10-12 16:38 UTC, Igmat requested changes
почему бы не сделать просто `isResetable`, `isConfirmable` и `isEndable`?

2023-10-13 08:47 UTC, Igmat approved these changes
LGTM

2023-10-13 08:47 UTC, merged